# Generated by Django 3.2.12 on 2022-08-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pincodes',
            field=models.ManyToManyField(blank=True, to='users.PinCode'),
        ),
    ]
