# Generated by Django 3.2.12 on 2022-08-02 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card', models.URLField(blank=True, max_length=255, null=True)),
                ('aadhar_card_data', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_card', models.URLField(blank=True, max_length=255, null=True)),
                ('pan_card_data', models.CharField(blank=True, max_length=255, null=True)),
                ('video_link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='other_documents',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('aadhar', 'Aadhar'), ('pan', 'Pan'), ('video', 'Video')], max_length=255),
        ),
        migrations.DeleteModel(
            name='AadharCard',
        ),
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
