# Generated by Django 3.2.12 on 2022-08-10 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220802_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('kyc', 'Kyc'), ('other', 'Other'), ('pan', 'Pan'), ('aadhar', 'Aadhar'), ('video', 'Video')], max_length=255),
        ),
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('punch_in', models.TimeField()),
                ('punch_out', models.TimeField()),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], default='absent', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
