# Generated by Django 3.2.12 on 2022-08-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_attendance_punch_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('done', 'done')], default='absent', max_length=255),
        ),
    ]
