# Generated by Django 3.2.12 on 2022-08-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='other_documents',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.BooleanField(default=False, help_text='False for (aadhar, pan and video) else True for (other and video)'),
        ),
    ]
