# Generated by Django 3.2.12 on 2022-08-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
