# Generated by Django 3.2.12 on 2022-08-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220811_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='aadhar_card_data',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='pan_card_data',
        ),
    ]
