# Generated by Django 3.2.12 on 2022-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_kyc_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('user', 'User'), ('admin', 'Admin'), ('kyc_verifier', 'KYC Verifier')], default='user', max_length=30),
        ),
    ]
