# Generated by Django 3.2.12 on 2022-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='slot_9_to_10',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
    ]
