# Generated by Django 3.2.12 on 2022-08-15 18:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_issue_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='issue',
            new_name='description',
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_10_to_11',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_11_to_12',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_12_to_1',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_1_to_2',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_2_to_3',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_3_to_4',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_4_to_5',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AddField(
            model_name='attendace',
            name='slot_5_to_6',
            field=models.BooleanField(default=False, help_text='False if operator is busy in this slot else True'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Operator'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('kyc', 'Kyc'), ('other', 'Other'), ('pan', 'Pan'), ('aadhar', 'Aadhar'), ('video', 'Video'), ('pending', 'Pending'), ('disabled', 'Disabled')], default='kyc', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
    ]
