# Generated by Django 3.2.12 on 2022-08-16 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220816_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendace',
            name='id',
        ),
        migrations.AddField(
            model_name='attendace',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
