# Generated by Django 3.2.12 on 2022-08-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220816_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendace',
            new_name='Attendance',
        ),
    ]
