# Generated by Django 3.2.12 on 2022-08-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_attendace_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='punch_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
