# Generated by Django 3.2.12 on 2022-08-16 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField(null=True)),
                ('slot_time', models.CharField(blank=True, choices=[('10_to_11', '10_to_11'), ('11_to_12', '11_to_12'), ('12_to_1', '12_to_1'), ('1_to_2', '1_to_2'), ('2_to_3', '2_to_3'), ('3_to_4', '3_to_4'), ('4_to_5', '4_to_5'), ('5_to_6', '5_to_6')], max_length=20, null=True)),
                ('operator_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('verification_image', models.URLField(blank=True, max_length=255, null=True)),
                ('booking_status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('completed', 'completed')], default='pending', max_length=20)),
                ('booking_type', models.CharField(blank=True, choices=[('create', 'create'), ('update', 'update')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
