# Generated by Django 3.2.12 on 2022-08-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='email',
        ),
    ]
