# Generated by Django 3.2.12 on 2022-08-15 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220810_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_slot_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_time',
            field=models.CharField(blank=True, choices=[('10_to_11', '10_to_11'), ('11_to_12', '11_to_12'), ('12_to_1', '12_to_1'), ('1_to_2', '1_to_2'), ('2_to_3', '2_to_3'), ('3_to_4', '3_to_4'), ('4_to_5', '4_to_5'), ('5_to_6', '5_to_6')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='verification_image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('completed', 'completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to='booking.Friend'),
        ),
    ]
