# Generated by Django 3.2.12 on 2022-08-19 15:16

from django.db import migrations, models
import services.utility


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=services.utility.create_booking_id, max_length=255),
        ),
    ]
