# Generated by Django 3.2.12 on 2022-08-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220816_0044'),
        ('booking', '0004_auto_20220816_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('create', 'create'), ('update', 'update')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='friends',
            field=models.ManyToManyField(to='booking.Friend'),
        ),
    ]
