# Generated by Django 3.2.12 on 2022-08-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
