# Generated by Django 3.2.12 on 2022-08-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.AddField(
            model_name='friend',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('create', 'create'), ('update', 'update')], max_length=20, null=True),
        ),
    ]
