# Generated by Django 3.2.12 on 2022-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preference',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=20, null=True),
        ),
    ]
