# Generated by Django 3.2.12 on 2022-08-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_booking_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot_time',
            field=models.CharField(blank=True, choices=[('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('12:00 PM - 1:00 PM', '12:00 PM - 1:00 PM'), ('1:00 PM - 2:00 PM', '1:00 PM - 2:00 PM'), ('2:00 PM - 3:00 PM', '2:00 PM - 3:00 PM'), ('3:00 PM - 4:00 PM', '3:00 PM - 4:00 PM'), ('4:00 PM - 5:00 PM', '4:00 PM - 5:00 PM'), ('5:00 PM - 6:00 PM', '5:00 PM - 6:00 PM'), ('9:00 AM - 12:00 PM', '9:00 AM - 12:00 PM'), ('12:00 PM - 3:00 PM', '12:00 PM - 3:00 PM'), ('3:00 PM - 6:00 PM', '3:00 PM - 6:00 PM')], max_length=20, null=True),
        ),
    ]
