# Generated by Django 3.2.12 on 2022-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='guideline',
            field=models.TextField(),
        ),
    ]
