# Generated by Django 3.2.12 on 2022-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='user_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('user', 'User'), ('admin', 'Admin'), ('kyc_verifier', 'KYC Verifier')], max_length=30, unique=True),
        ),
    ]
