# Generated by Django 3.2.12 on 2022-08-07 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20220808_0046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_for',
        ),
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
