# Generated by Django 3.2.12 on 2022-08-15 18:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20220810_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelines',
            name='guideline',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='guidelines',
            name='user_type',
            field=models.CharField(choices=[('operator', 'Operator'), ('user', 'User'), ('admin', 'Admin')], max_length=30, unique=True),
        ),
    ]
